name: Feature Workflow

on: [ push ]

jobs:
  test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'

      - name: Test
        run: make test

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
